### ISSUE TITLE
App behaving different than in tutorial

### ISSUE THREAD

**Issue by viktapas** [viktapas/MasterFlowGit#1]
The app behaving differently but doing same jobs and also codes are different by default if we follow the tutorial (I had to edit the default codes). why this? Because I am using higher android API level?

Links:
Code: https://github.com/vikaskumar-vsk/MasterFlowGit/blob/master/app/src/main/java/com/vikaskumar/vsk/masterflow/dummy/DummyContent.java
Tutorial: https://youtu.be/iNzrUu784dY?t=7m2s

**Comment by imflash217** [comment]
@vikaskumar-vsk , what is the difference you are pointing to, i see that the appperforms smilae to wht is shown in video. The only difference i see is how the **Details View** which is due to how you have defined it in **DetailsView......java** file and it looks more modern compared to video's as you are using higher Android API level (and hence Material Design).
